name: buddy
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.4
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.1.0
  devicelocale: ^0.6.0
  dice_bear: ^0.1.5
  dio: ^5.1.0
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  json_annotation: ^4.8.0
  logger: ^1.2.2
  package_info_plus: ^1.4.3+1
  pinput: ^2.2.31
  responsive_builder: ^0.6.3
  shared_preferences: ^2.0.18
  sprintf: ^7.0.0
  version_tracker: ^2.1.1
  waterfall_flow: ^3.0.2
  webview_flutter: ^4.0.6

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true

  assets:
    - assets/gifs/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Regular.ttf
        - asset: assets/fonts/ClashDisplay-Extralight.ttf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/ClashDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Bold.ttf
          weight: 700

