// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9WMSUyh-R3HV7z63NJfhw8Wx2-oSlfUM',
    appId: '1:76594779075:web:6a2001cc5f73bfb7082376',
    messagingSenderId: '76594779075',
    projectId: 'buddy-prod-c7587',
    authDomain: 'buddy-prod-c7587.firebaseapp.com',
    storageBucket: 'buddy-prod-c7587.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYWXeBjng6_INs28BiMjiUs9QEEFD1Pc',
    appId: '1:76594779075:android:98975e0a6f9105e8082376',
    messagingSenderId: '76594779075',
    projectId: 'buddy-prod-c7587',
    storageBucket: 'buddy-prod-c7587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GHuTgcsR_aLZ5-9cP2uQ4x3Io8gA_ww',
    appId: '1:76594779075:ios:3fb6c800fc57cb09082376',
    messagingSenderId: '76594779075',
    projectId: 'buddy-prod-c7587',
    storageBucket: 'buddy-prod-c7587.appspot.com',
    androidClientId: '76594779075-hlnjf3adlgb3e6kqls6blmnokr3sfdh3.apps.googleusercontent.com',
    iosClientId: '76594779075-292km4jumia88qv4iic1n14ic627tg40.apps.googleusercontent.com',
    iosBundleId: 'com.morpheus.buddy',
  );
}
