// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZFcpY951MinBO_LEBOdrI2gsrs4TNQA',
    appId: '1:843432754231:web:0a47f1c0e0f16d63b253b2',
    messagingSenderId: '843432754231',
    projectId: 'buddy-dev-1d63f',
    authDomain: 'buddy-dev-1d63f.firebaseapp.com',
    storageBucket: 'buddy-dev-1d63f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFZz7D8aYJkJd1fvQRxMYJBSGXMt0oMA',
    appId: '1:843432754231:android:39e78a811936285fb253b2',
    messagingSenderId: '843432754231',
    projectId: 'buddy-dev-1d63f',
    storageBucket: 'buddy-dev-1d63f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuEPna25ZCne6H4jk77mzIEBisXPXMdDY',
    appId: '1:843432754231:ios:684e75629d328209b253b2',
    messagingSenderId: '843432754231',
    projectId: 'buddy-dev-1d63f',
    storageBucket: 'buddy-dev-1d63f.appspot.com',
    androidClientId: '843432754231-e01828bdr9870aqgv2fpupkb6mnmvjpo.apps.googleusercontent.com',
    iosClientId: '843432754231-ufm0l51uhf8vqk4i9e7g4ethfe4ier4f.apps.googleusercontent.com',
    iosBundleId: 'com.morpheus.buddy.dev',
  );
}
